sonar.projectKey=Csontikka_ha-mikrotik-extended
sonar.organization=csontikka
sonar.sources=custom_components/mikrotik_extended
sonar.tests=tests
sonar.python.version=3.13
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
